DROP TABLE customer_oto_bi;;
CREATE TABLE DEPT_OTO(
		 DEPT_NO NUMBER PRIMARY KEY,
		 DEPT_NAME VARCHAR2(30));

		 
DROP TABLE address_oto_bi;		 
CREATE TABLE EMP_OTO(
		EMP_ID NUMBER PRIMARY KEY,
		 EMP_NAME VARCHAR2(30),
		 EMP_SAL NUMBER,
		DEPT_NO NUMBER,
		CONSTRAINT fk_dept FOREIGN KEY(DEPT_NO) 
 REFERENCES DEPT_OTO(DEPT_NO));
 
 SELECT * FROM customer_oto_bi;
 
  SELECT * FROM address_oto_bi;